site_name: Cursos
theme: flatly
repo_url: 'https://github.com/GomezMunera/cursos-ing'
site_description: 'Cursos dictados en la facultad de ingeniería de la universidad de Antioquia'
nav:
- 'Inicio': 'index.md'
- Robótica Industrial:
    - 'Clases':
        - 'Clase 1': 'clases/clase1.md'
        - 'Clase 2': 'clases/clase2.md'
        - 'Clase 3': 'clases/clase3.md'
        - 'Clase 4': 'clases/clase4.md'
        - 'Clase 5': 'clases/clase5.md'
        - 'Clase 6': 'clases/clase6.md'
        - 'Clase 7': 'clases/clase7.md'
        - 'Clase 8': 'clases/clase8.md'
        - 'Clase 9': 'clases/clase9.md'
        - 'Clase 10': 'clases/clase10.md'
        - 'Clase 11': 'clases/clase11.md'
        - 'Clase 12': 'clases/clase12.md'
        - 'Clase 13': 'clases/clase13.md'
        - 'Clase 14': 'clases/clase14.md'
        - 'Clase 15': 'clases/clase15.md'
        - 'Clase 16': 'clases/clase16.md'
        - 'Clase 17': 'clases/clase17.md'
        - 'Clase 18': 'clases/clase18.md'
        - 'Clase 19': 'clases/clase19.md'
        - 'Clase 20': 'clases/clase20.md'
    - 'Laboratorios':
        - 'Lab 1': 'labs/lab1.md'
        - 'Lab 2': 'labs/lab2.md'
        - 'Lab 3': 'labs/lab3.md'
        - 'Lab 4': 'labs/lab4.md'
        - 'Lab 5': 'labs/lab5.md'
        - 'Lab 6': 'labs/lab6.md'
- Guía:
    - 'Escribiendo': 'guia/Escribiendo.md'
    - 'Estilo': 'guia/estilo.md'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/GomezMunera'
    - type: 'facebook'
      link: 'https://www.facebook.com/johnanderson.munera'
    - type: 'linkedin'
      link: 'www.linkedin.com/in/jagomezmunera'
